require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BallsController do

  # This should return the minimal set of attributes required to create a valid
  # Ball. As you add validations to Ball, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BallsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all balls as @balls" do
      ball = Ball.create! valid_attributes
      get :index, {}, valid_session
      assigns(:balls).should eq([ball])
    end
  end

  describe "GET show" do
    it "assigns the requested ball as @ball" do
      ball = Ball.create! valid_attributes
      get :show, {:id => ball.to_param}, valid_session
      assigns(:ball).should eq(ball)
    end
  end

  describe "GET new" do
    it "assigns a new ball as @ball" do
      get :new, {}, valid_session
      assigns(:ball).should be_a_new(Ball)
    end
  end

  describe "GET edit" do
    it "assigns the requested ball as @ball" do
      ball = Ball.create! valid_attributes
      get :edit, {:id => ball.to_param}, valid_session
      assigns(:ball).should eq(ball)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ball" do
        expect {
          post :create, {:ball => valid_attributes}, valid_session
        }.to change(Ball, :count).by(1)
      end

      it "assigns a newly created ball as @ball" do
        post :create, {:ball => valid_attributes}, valid_session
        assigns(:ball).should be_a(Ball)
        assigns(:ball).should be_persisted
      end

      it "redirects to the created ball" do
        post :create, {:ball => valid_attributes}, valid_session
        response.should redirect_to(Ball.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ball as @ball" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ball.any_instance.stub(:save).and_return(false)
        post :create, {:ball => {  }}, valid_session
        assigns(:ball).should be_a_new(Ball)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ball.any_instance.stub(:save).and_return(false)
        post :create, {:ball => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ball" do
        ball = Ball.create! valid_attributes
        # Assuming there are no other balls in the database, this
        # specifies that the Ball created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ball.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => ball.to_param, :ball => { "these" => "params" }}, valid_session
      end

      it "assigns the requested ball as @ball" do
        ball = Ball.create! valid_attributes
        put :update, {:id => ball.to_param, :ball => valid_attributes}, valid_session
        assigns(:ball).should eq(ball)
      end

      it "redirects to the ball" do
        ball = Ball.create! valid_attributes
        put :update, {:id => ball.to_param, :ball => valid_attributes}, valid_session
        response.should redirect_to(ball)
      end
    end

    describe "with invalid params" do
      it "assigns the ball as @ball" do
        ball = Ball.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ball.any_instance.stub(:save).and_return(false)
        put :update, {:id => ball.to_param, :ball => {  }}, valid_session
        assigns(:ball).should eq(ball)
      end

      it "re-renders the 'edit' template" do
        ball = Ball.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ball.any_instance.stub(:save).and_return(false)
        put :update, {:id => ball.to_param, :ball => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ball" do
      ball = Ball.create! valid_attributes
      expect {
        delete :destroy, {:id => ball.to_param}, valid_session
      }.to change(Ball, :count).by(-1)
    end

    it "redirects to the balls list" do
      ball = Ball.create! valid_attributes
      delete :destroy, {:id => ball.to_param}, valid_session
      response.should redirect_to(balls_url)
    end
  end

end
